export const COURSE_REQUEST_LIST = "COURSE_REQUEST_LIST";
export const COURSE_SUCCESS_LIST = "COURSE_SUCCESS_LIST";
export const COURSE_FAIL_LIST = "COURSE_FAIL_LIST";


export const TOPCOURSEREGISTERED_REQUEST_LIST = "TOPCOURSEREGISTERED_REQUEST_LIST";
export const TOPCOURSEREGISTERED_SUCCESS_LIST = "TOPCOURSEREGISTERED_SUCCESS_LIST";
export const TOPCOURSEREGISTERED_FAIL_LIST = "TOPCOURSEREGISTERED_FAIL_LIST";

export const TOPCOURSENEW_REQUEST_LIST = "TOPCOURSENEW_REQUEST_LIST";
export const TOPCOURSENEW_SUCCESS_LIST = "TOPCOURSENEW_SUCCESS_LIST";
export const TOPCOURSENEW_FAIL_LIST = "TOPCOURSENEW_FAIL_LIST";

export const INCREMENT_VIEW_COURSE = "INCREMENT_VIEW_COURSE";
