export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";


export const USER_SENDOTP_REQUEST = "USER_REGISTER_REQUEST";
export const USER_SENDOTP_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_SENDOTP_FAIL = "USER_REGISTER_FAIL";


export const CONFIRM_OTP = "CONFIRM_OTP";