export const ADD_ITEM_WISHLIST = "ADD_ITEM_WISHLIST";
export const REMOVE_ITEM_WISHLIST = "REMOVE_ITEM_WISHLIST";


export const ITEM_REQUEST_WISHLIST = "ITEM_REQUEST_WISHLIST";
export const ITEM_SUCCESS_WISHLIST = "ITEM_SUCCESS_WISHLIST";
export const ITEM_FAIL_WISHLIST = "ITEM_FAIL_WISHLIST";
